apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  labels:
    app: nginx
  name: monnginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: monnginx

