apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    tier: front
  name: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
  selector:
    app: nginx
    tier: front
